build:
  install:
    image: golang
    pull: true
    commands:
      - make install
      - make lint
      - make test
    when:
      branch: "master"

  pull-request:
    image: golang
    pull: true
    commands:
      - make install
      - make lint
      - make test
    when:
      event: "pull_request"



  run:
    image: golang
    pull: true
    commands:
      - go build
      - $(pwd)/Drone
    when:
      branch: "master"
      success: true
